name = "black-hearted wizardry"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96749776d77dd57b7f2e9403da79e9515ddb52fbe8c888ad84b4703a78a1db91"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
